### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by kokokostya** [souramoo/commentoplusplus#104]
Hey. Great job maintaining this fork!

Just deployed to Heroku with the following SMTP settings:
`COMMENTO_SMTP_HOST: smtp.gmail.com`
`COMMENTO_SMTP_PORT: 587`
`COMMENTO_SMTP_USERNAME: mymail@gmail.com`
`COMMENTO_SMTP_PASSWORD: mypassword`
`COMMENTO_SMTP_FROM_ADDRESS: mymail@gmail.com`

...and I keep receiving **535-5.7.8 Username and Password not accepted** error in my log when I try to create a user even though the credentials are definitely correct.

[This Google help article](https://support.google.com/accounts/answer/6010255#zippy=%2Cuse-an-app-password) says:

> From May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password

I'm guessing this could be the reason, isn't it?

Thanks!

**Comment by souramoo** [comment]
Thank you for your message! Yes, gmail no longer supports this form of usage. To fix this, you should use their app passwords instead, which basically works the same way from commento's point of view (replace your SMTP password with an app password) but with the benefit that it can easily be revoked if it goes missing. 

https://support.google.com/accounts/answer/185833?hl=en
