### ISSUE TITLE
How to use this repo with docker-compose ?

### ISSUE THREAD

**Issue by MoryCorp** [souramoo/commentoplusplus#11]
Hi,

Sorry this it not really an issue.
I'm currently still using the official (dead) commento with the official docker-compose.yml

Is there a chance I could just replace "registry.gitlab.com/commento/commento:SET_VERSION" to an URL to this repo to make it works ?

Thanks

**Comment by souramoo** [comment]
Hey,

No problem! You can use this repo with docker-compose but you just need to replace that line with `build: .` :) Have updated the repo for you, remember to add in the rest of the environment variables!

**Comment by MoryCorp** [comment]
Thanks, that was a really fast answer.
Everything works just fine.
Good work and thanks for keep this project alive
