### ISSUE TITLE
Is commento++ still maintained?

### ISSUE THREAD

**Issue by collector-ynh** [souramoo/commentoplusplus#152]
Hello, I want to use commento++ which is a very useful tool, but I noticed that the last update was in 2022, so I am hesitant to integrate it into my site!

 Do you still plan to maintain this application or do you want to abandon it?

**Comment by souramoo** [comment]
Hey! Still being maintained - just that a lot of the features are fairly stable so haven't required a major update, so working on the best way to add new ones :)
