### ISSUE TITLE
Can not set mail notification when using social login

### ISSUE THREAD

**Issue by Ben02** [souramoo/commentoplusplus#16]
![](https://i.loli.net/2021/01/17/B2H5UXoTzLQ3E1r.png)

The "Notification Setting" link is not appended due to the line below. People using social login are unable to set the mail notification. 

https://github.com/souramoo/commentoplusplus/blob/a020fd622f0c710fff737474215f04c0ead04487/frontend/js/commento.js#L381

That file was changes by [this commit](https://github.com/souramoo/commentoplusplus/commit/86f0b4f0fd79eef404c7a572332e29968a55bd4b). I wonder why the notification setting link should not be appended.

**Comment by souramoo** [comment]
Ah yes, I removed this to make it look a bit less cramped on mobiles. Will add it back in.

**Comment by souramoo** [comment]
![image](https://user-images.githubusercontent.com/11202149/110681096-550d1200-81d1-11eb-86e3-5c8ffd8d0f38.png)
Replaced this with icons to fix mobile formatting and improve interface in 673ea65
