### ISSUE TITLE
cant create account

### ISSUE THREAD

**Issue by stephenajulu** [souramoo/commentoplusplus#17]
Hi, thank you for this. Been looking for a comment system i could host on heroku for a while.
Now the issue i am facing is that i can't create and account despite setting the option to true.
Did i miss something in the readme or is this an issue i have to fix.
If so kindly help me. 
I didn't set the smtp options, only the domain name and changed account the option to true

**Comment by candideu** [comment]
Were you able to solve this? Having the same issue
