### ISSUE TITLE
Commenter photo does not support png images

### ISSUE THREAD

**Issue by FrancisTurner** [souramoo/commentoplusplus#19]
I tried to personalize my commenting presence on someone's blog using commentoplusplus by clicking on the settings (edit profile) link in the comments area.

I gave it a URL to a .png
![image](https://user-images.githubusercontent.com/991242/110258160-6cfe4f00-7fa1-11eb-9f5f-e2f32e737086.png)

that is valid and exists (https://micronetia.devtru.st/content/images/2021/01/micronetia-square.png )

It does not display in the comments. Instead there is a blank circle
![image](https://user-images.githubusercontent.com/991242/110258202-a8991900-7fa1-11eb-8247-5ec6257697a3.png)

and if I right click and view image I get a text message:
JPEG decode failed: invalid JPEG format: missing SOI marker

When I change the link to one that is a jpeg one (https://micronetia.devtru.st/content/images/micronetia.jpg )  it works. 

The text surrounding the photo box does not mention that jpeg is the only supported format:

Photo
Use an external image hosting service such as Imgur and enter the direct link to the image here. Changes to your profile photo may take a few hours to reflect. Maximum file size allowed is 128 KiB.

**Comment by souramoo** [comment]
Thank you for reporting this! This is definitely a bug.

I have now fixed it as of 0702fdc :)

**Comment by FrancisTurner** [comment]
new binary built and applied. confirmed fixed
