### ISSUE TITLE
Make SMTP configuration optional

### ISSUE THREAD

**Issue by nirvdrum** [souramoo/commentoplusplus#2]
When using the Heroku template, the SMTP configuration is required even though it's optional with Commento. Simply using `""` for the values doesn't help because it looks like Commento checks for the presence of the env var, rather than the presence of a non-empty value. I found that Commento wouldn't start up properly if I put `""` in for values, but worked fine if I deleted the `COMMENTO_SMTP_HOST` value from the app config in Heroku.

**Comment by souramoo** [comment]
Very good point, have fixed this in 66514f3279616a3e2d14bf14bcd7f9ccbf28bfd4 :)
