### ISSUE TITLE
Running commento++ in subdirectory

### ISSUE THREAD

**Issue by Targunitoth** [souramoo/commentoplusplus#27]
_Originally posted by @souramoo in https://github.com/souramoo/commentoplusplus/issues/26#issuecomment-808469970

Should now be fixed from 07e718a onwards, please test this out and report back if this is still an issue!_

Thank you for your fast fix.
I could test it today, but I just get a blank page back.
Before the fix (2da3575) I got a 404.

**Comment by souramoo** [comment]
Alright I set up a proper test for this and confirmed it wasn't working, should now be fixed from 84ffbc2 onwards

My startup script:
```
export COMMENTO_ORIGIN=http://localhost:8082/commento
export COMMENTO_CDN_PREFIX=$COMMENTO_ORIGIN
```

And now everything seems to load! Once ORIGIN is set to /commento, the CDN_PREFIX will need it too, and then everything will be served out of /commento and you can reverse proxy to it easily using, e.g. Caddy. Hope this helps!
