### ISSUE TITLE
Cannot deploy with Heroku: content of app.json is invalid

### ISSUE THREAD

**Issue by nirmalhk7** [souramoo/commentoplusplus#28]
I'm not able to deploy with Heroku: it gives me this error:
![Screenshot_2021-04-16 Create New App Heroku](https://user-images.githubusercontent.com/25480443/114969711-952d7780-9e96-11eb-8979-2976542d5126.png)

**Comment by souramoo** [comment]
Thanks for the bug report, this was a regression introduced in commit 93c05e9ead2913254187f6cbfe63b04d7e4c0927 oops! Fixed now :)
