### ISSUE TITLE
[FEATURE REQ] Show all comments via Commento UI

### ISSUE THREAD

**Issue by rusty1281** [souramoo/commentoplusplus#29]
Hello,

atm, only comments that are visible via the UI are ones that are waiting for moderation view. Would it be possible to view all the comments in some format so we don't have to review them via DB?

tnx in advance!

**Comment by souramoo** [comment]
Added in 542dcef under a subtab in the moderation dashboard!

![image](https://user-images.githubusercontent.com/11202149/115936817-2a7bcd80-a48e-11eb-8c5f-a1725e55be30.png)
