### ISSUE TITLE
Implement i18 for internationalization

### ISSUE THREAD

**Issue by svandegar** [souramoo/commentoplusplus#3]
Hello,

Thank you so much for your work on this project. Hopefully the original maintainer merges all your PR soon.

In the meantime, I was wondering if there was a way to merge this PR into your fork: https://gitlab.com/commento/commento/-/merge_requests/153

I'll try to submit a PR here.

**Comment by souramoo** [comment]
Thanks, me too! I think i18n is a great idea, and I've copied your PR from gitlab over here and refactored it to work with the latest commit :)

**Comment by souramoo** [comment]
Okay I'm not sure what I did with git but it's merged now as of 23277f40e6d9806f03d3cbff51404331d0f8da9b !

**Comment by svandegar** [comment]
Wonderful!

Thank you so much!

Sent from my mobile phone.

Le 26 déc. 2020 à 20:56, Souradip Mookerjee <notifications@github.com> a écrit :

﻿

Okay I'm not sure what I did with git but it's merged now as of 23277f4<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsouramoo%2Fcommentoplusplus%2Fcommit%2F23277f40e6d9806f03d3cbff51404331d0f8da9b&data=04%7C01%7C%7Ccbcadf8034964e0dab8908d8aa023119%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637446273672937857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2v%2Fmv9z3K2X4B0DK1RbFVhzRa5U%2BeHvxnI0UfbjUbhE%3D&reserved=0> !
