### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by jeremy-jameson** [souramoo/commentoplusplus#30]
There have been a number of commits since the last release (https://github.com/souramoo/commentoplusplus/releases/tag/v1.8.4).

I am currently evaluating whether to use Commento or Commento++ and it would be really nice to see the "Powered by Commento" vs. "Powered by Commento++" message in the footer.

At this point, I am leaning towards Commento++. However, since I am using the [Docker image produced over on GitLab](https://gitlab.com/caroga/commentoplusplus-docker), there are a number of changes -- including the updated footer message -- that are not included in the v1.8.4 image.

Would you please create a release so I can then request @caroga to build a new version of the Docker image? Thanks...and, more importantly, thank you for all the time and effort you have invested in improving Commento.

**Comment by souramoo** [comment]
Thanks for the kind words! I've just pushed a new precompiled release at https://github.com/souramoo/commentoplusplus/releases/tag/v1.8.5 :)

Will see what I can do in automating new docker images to be made too, to help streamline this process

**Comment by Caroga** [comment]
Hi! I have totally missed this call. I will build the new images today, no worries! 👍🏻

**Comment by Caroga** [comment]
Image is building, will be uploaded within a few minutes @jeremy-jameson .

@souramoo I could create a trigger on these releases so the images are built instantly. I don't mind this at all and would like to do so to save you time for looking into this process as I already have it running. So if you don't mind that it's not having your name on the images then we could just leave it this way..

I'm also still hoping to contribute this to the upstream instead as originally it (still) is a project from @adtac.

**Comment by Caroga** [comment]
@jeremy-jameson New version is published.
