### ISSUE TITLE
Delete user account

### ISSUE THREAD

**Issue by LawGain** [souramoo/commentoplusplus#31]
First of all, thank you for continuing Commento's development. Because of you it is possible to keep using Commento at all.
I have a few feature requests that I would be happy to see implemented if possible.

Could you please include a way for the user to delete their account? Alternatively also a possibility from the dashboard GUI for the admin. Because at the moment it's hardly possible to run Commento GDPR compliant once you enable email login.

**Comment by souramoo** [comment]
Thanks, and good idea; I will see what I can do!

**Comment by LawGain** [comment]
Wow, that was a fast answer.
Thanks in advance for at least looking at it.

**Comment by souramoo** [comment]
Implemented from 5825db8 onwards! :) Now users can go into their profile settings and delete their account.

![image](https://user-images.githubusercontent.com/11202149/115935101-601eb780-a48a-11eb-8c64-1c4529f7b68a.png)
![image](https://user-images.githubusercontent.com/11202149/115935135-70cf2d80-a48a-11eb-801c-e6b481fc235f.png)
