### ISSUE TITLE
No names when E-Mail login disabled

### ISSUE THREAD

**Issue by deployn** [souramoo/commentoplusplus#35]
Hello :)
When you disable E-Mail login an anonymous user cannot use any name, it always reverts into "Anonymous", because the checkbox is disabled and can not be unclicked.

![image](https://user-images.githubusercontent.com/54767886/116009504-69d72500-a61a-11eb-93bc-3d9d3300d536.png)

**Comment by jackbenny** [comment]
I'm also looking for a way to use names when E-mail login is disabled.

**Comment by souramoo** [comment]
Fixed!
