### ISSUE TITLE
Can not send mails via anonymous smtp login

### ISSUE THREAD

**Issue by Targunitoth** [souramoo/commentoplusplus#36]
Thank you for fixing #27, it is now working fine.
But I have to come up with the next issue: I have problems with sending anonymous emails. The offical commento sends out the mails, but comento++ is just crashing. Here is the log:

>Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] version.go:13 versionPrint(): starting Commento v1.8.6
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] database_connect.go:20 dbConnect(): opening connection to postgres: postgres://commento:redacted@127.0.0.1:5432/commento?sslmode=disable
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] database_migrate.go:47 migrateFromDir(): 32 migrations already installed, looking for more
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] database_migrate.go:91 migrateFromDir(): none found
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] smtp_configure.go:28 smtpConfigure(): configuring smtp: exchange.redacted-mailserver-ip
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [WARNING] smtp_configure.go:30 smtpConfigure(): no SMTP username/password set, Commento will assume they aren't required
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] smtp_templates.go:43 smtpTemplatesLoad(): loading templates: [confirm-hex reset-hex domain-export domain-export-error]
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] sigint.go:22 sigintCleanupSetup(): setting up SIGINT cleanup
Apr 26 12:16:48 servername commento[543680]: 2021/04/26 12:16:48 [INFO] router.go:38 routesServe(): starting server on 127.0.0.1:37531
Apr 26 12:16:50 servername commento[543680]: 2021/04/26 12:16:50 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
Apr 26 12:16:53 servername commento[543680]: 2021/04/26 12:16:53 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
Apr 26 12:16:56 servername commento[543680]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 26 12:16:56 servername commento[543680]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8ba7d2]
Apr 26 12:16:56 servername commento[543680]: goroutine 53 [running]:
Apr 26 12:16:56 servername commento[543680]: net/smtp.(*Client).Auth(0xc0002c6600, 0x0, 0x0, 0x0, 0x0)
Apr 26 12:16:56 servername commento[543680]: #011/usr/lib/go-1.13/src/net/smtp/smtp.go:204 +0xd2
Apr 26 12:16:56 servername commento[543680]: main.smtpSendMail(0xc000341250, 0xe, 0xc00036e1c0, 0x10, 0xa47027, 0x18, 0xc000169c00, 0x66, 0xc0005ac000, 0x106e, ...)
Apr 26 12:16:56 servername commento[543680]: #011/home/commento/commentoplusplus/api/smtp_send.go:61 +0x731
Apr 26 12:16:56 servername commento[543680]: main.smtpEmailNotification(0xc000341250, 0xe, 0xc00036e1c0, 0x10, 0xa4238a, 0x12, 0xc0003411d0, 0xf, 0xc00007ea20, 0x5a, ...)
Apr 26 12:16:56 servername commento[543680]: #011/home/commento/commentoplusplus/api/smtp_email_notification.go:46 +0x61b
Apr 26 12:16:56 servername commento[543680]: main.emailNotificationModerator(0xc0003411d0, 0xf, 0xc00002c840, 0x40, 0xc0003411e0, 0x8, 0x1c1badc0, 0xed7f50f85, 0xc00022fda0, 0xc0003411e8, ...)
Apr 26 12:16:56 servername commento[543680]: #011/home/commento/commentoplusplus/api/email_notification_new.go:63 +0x5ea
Apr 26 12:16:56 servername commento[543680]: main.emailNotificationNew(0xc0003411d0, 0xf, 0xc00002c840, 0x40, 0xc0003411e0, 0x8, 0x1c1badc0, 0xed7f50f85, 0xc00022fda0, 0xc0003411e8, ...)
Apr 26 12:16:56 servername commento[543680]: #011/home/commento/commentoplusplus/api/email_notification_new.go:152 +0x18f
Apr 26 12:16:56 servername commento[543680]: created by main.commentNewHandler
Apr 26 12:16:56 servername commento[543680]: #011/home/commento/commentoplusplus/api/comment_new.go:151 +0xb6f
Apr 26 12:16:56 servername systemd[1]: commento.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 26 12:16:56 servername systemd[1]: commento.service: Failed with result 'exit-code'.

Do you have an idea or do you need more information?
Thank you!

**Comment by souramoo** [comment]
Sorry it took me a bit of time to get round to looking into this but it's actually a fairly simple fix in https://github.com/souramoo/commentoplusplus/commit/432309b98ea9456e62467ad4edd5aa23df9412ee - so should work now, let me know if there are any further problems! :) (I haven't tested this as I do not have an anon smtp relay available but theoretically should fix the null pointer reference...)
