### ISSUE TITLE
No analytics since swith to CommentoPLUSPLUS

### ISSUE THREAD

**Issue by magicgg91** [souramoo/commentoplusplus#37]
Hello,
I've switched a month ago to CommentoPLUSPLUS but I don't have anymore views statistics displayed. Comments statistics are OK.
I've tried to deactivate and reactivate again, but no resolution with this.
Thanks for help.

**Comment by souramoo** [comment]
Have disabled by default to save space on postgre on heroku, but you can easily reenable with

```
export COMMENTO_ENABLE_LOGGING=true
```

or similar to set that environment variable to true :)
