### ISSUE TITLE
Make Websockets optional

### ISSUE THREAD

**Issue by dehgriff** [souramoo/commentoplusplus#4]
I'd be running Commento++ behind a reverse proxy, and don't really want to let websockets through. For a commenting service it might be a bit overkill. Could this be a configurable feature? I love what you've done though, and that you are pushing Commento forward.

**Comment by souramoo** [comment]
Thanks for the lovely feedback!

I've added some flags to do a few variations on this in the latest commits (397d6c00c05458271306a0fde144d49d1b554a41 onwards) (and documented this in the README, may need to revamp the docs soon to be a bit clearer and less dependent on the commento.io docs which currently have an expired certificate):
- `data-no-websockets="true"` - Disables websocket functionality in favour of HTTP polling to have the same live reload functionality in a situation where websockets aren't allowed (e.g. a reverse proxy)
- `data-no-livereload="true"` - Disabled all hot reload functionality (this supercedes the above flag) - all comments are loaded once and only once on page load.

usage example:
```
<script defer src="https://chat.mookerj.ee/js/commento.js" data-no-websockets="true"></script>
```

**Comment by dehgriff** [comment]
Awesome, that's brilliant. Thanks very much.

David
