### ISSUE TITLE
Github Action for automatically building Docker images

### ISSUE THREAD

**Issue by TannerGabriel** [souramoo/commentoplusplus#57]
I noticed that the repo currently does not have some CI/CD functionality to automatically build Docker images when it is updated, or a new release comes out. Therefore the `latest` tag of `caroga/commentoplusplus` Docker image has not been updated with the newest changes.

Let me know if you think that such functionality would be useful for the repository. If so, we could implement it similar to how it is implemented in the [ion-sfu](https://github.com/pion/ion-sfu/blob/master/.github/workflows/docker-allrpc.yaml) repository.

**Comment by souramoo** [comment]
Yes this functionality would be most welcomed for a streamlined deployment process!
