### ISSUE TITLE
How to modify SMTP configuration

### ISSUE THREAD

**Issue by simonmeggle** [souramoo/commentoplusplus#70]
Hi, 

what is the receommended way to _change_ SMTP settings? 
It does not seemd to be enough to change the environment variables and restart the docker-compose setup. In the commento startup log I always see then the old SMTP data. 
Only deleting the commento volume did the trick; the database got initialized then with the new values. 
But I assume there is another way, too... 
Thanks,
Simon

**Comment by RealOrangeOne** [comment]
SMTP settings are only read from the environment, not the database. I suspect either something else was keeping hold of them, or the restart wasn't actually applying.

**Comment by souramoo** [comment]
I suspect this is more of a docker usage issue than a commento issue as we don't cache these details anywhere and they are indeed read directly from the environment variables - closing for now but please do comment if you are able to provide a video or similar of this issue happening (with dummy credentials)
