### ISSUE TITLE
Unable to Moderate Comments as the Admin, Login

### ISSUE THREAD

**Issue by candideu** [souramoo/commentoplusplus#73]
Hello! I've been experiencing some issues with moderating my comments. and with logging into the widget.

# Unable to Moderate Comments as the Admin
When I click on "Delete" or "Approve, I get the error that I'm not allowed to access that, despite being the admin:
![image](https://user-images.githubusercontent.com/55474996/153951609-47c59f82-189a-42b8-8f5b-e5e9824b8e05.png)

# Issues Logging In Using Admin Credentials
I've also been having trouble with logging into the comment section with my admin credentials (same ones used in the Heroku app's dashboard):
![image](https://user-images.githubusercontent.com/55474996/153952100-20be0921-066f-48cd-8535-b77af5a1317b.png)

I get this error:
![image](https://user-images.githubusercontent.com/55474996/153952040-c5ce3fa5-09af-491e-82f3-1abe6edf885f.png)

**Comment by BBaoVanC** [comment]
I think I'm getting that first issue myself too. Just now set up a server and am trying to use it on my website.

**Comment by candideu** [comment]
The latest update solved this issue, thanks to this pull request: https://github.com/souramoo/commentoplusplus/pull/100
