### ISSUE TITLE
Add contributor guidelines?

### ISSUE THREAD

**Issue by olof-nord** [souramoo/commentoplusplus#79]
Many projects which aims to be ran as a community, adds a contributing guideline.

Quoting from the [GitHub documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors):

> For the repository owner, contribution guidelines are a way to communicate how people should contribute.
> For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.

**Comment by olof-nord** [comment]
Here is the contributing guide for GitHub itself: https://github.com/github/docs/blob/main/CONTRIBUTING.md

**Comment by souramoo** [comment]
Thanks for the suggestion, added!
