### ISSUE TITLE
Frontend: Update gulp-sass as to support Node v16

### ISSUE THREAD

**Issue by olof-nord** [souramoo/commentoplusplus#91]
> Current version of node-sass prevents building with Node v16 (it would be nice to update to the last LTS), so let's use Node v14 for now.

The frontend package is using `v4.0.1` of the library, the most current version is `v5.1.0`.

See PR #89 for the full details.

**Comment by Wonderfall** [comment]
Also worth noting that `node-sass` itself, while still maintained at the moment, [seems deprecated](https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate).

**Comment by souramoo** [comment]
Thanks for flagging this; fixed in edc2a92! :) This was also needed to ensure things would compile on github actions for CI purposes as they have node v16 too.
