### ISSUE TITLE
Is Twitter OAuth still supported?

### ISSUE THREAD

**Issue by olof-nord** [souramoo/commentoplusplus#92]
I have tried to set up Twitter OAuth1 for commentoplusplus using the described two environment variables (COMMENTO_TWITTER_KEY and COMMENTO_TWITTER_SECRET), but without success.

Where I believe I am failing is on the twitter side, in the [Developer Portal](https://developer.twitter.com/en/portal/dashboard).

If the OAuth integration does work, does anyone know what I should configure there?
Especially at the "User authentication settings" for the app.

Here is what I use at the moment:

OAuth 2.0: off
OAuth 1.0a: on

OAuth 1.0a settings

Request email from users: on (as per [this](https://gitlab.com/commento/docs/-/issues/11) issue, which currently is two years old)
App permissions: Read and Write
Callback URL: https://commento.my.domain/api/oauth/twitter/callback
Website URL: https://commento.my.domain

This does not work, and I keep seeing errors in the logs:

```log
commento       | 2022/04/06 12:27:52 [ERROR] oauth_twitter_redirect.go:26 twitterRedirectHandler(): cannot get temporary twitter credentials: OAuth server status 401, {"errors":[{"code":32,"message":"Could not authenticate you."}]}
```

And in the browser the following error is displayed when trying to log in:

```log
error: An internal error has occurred. If you see this repeatedly, please contact support.
```

Now, are my OAuth settings correct?
Where should I get the two values from, from Consumer Keys, Access Token and Secret  or OAuth 2.0 Client ID and Client Secret?

Any info would be greatly appreciated.

**Comment by souramoo** [comment]
Hi,

Twitter OAuth certainly does work, it is enabled on the demo site at https://demo.souradip.com/chat.html

You are correct in using OAuth 1.0a. You will need to add the Access token and secret and put them into the environment variables COMMENTO_TWITTER_KEY and COMMENTO_TWITTER_SECRET

You click the top tab that says "Keys and tokens" next to "settings" after accessing your app settings at https://developer.twitter.com/en/portal


![image](https://user-images.githubusercontent.com/11202149/162062796-b8fd7fb3-6004-4ba3-9770-60fe257c1cfa.png)

**Comment by olof-nord** [comment]
Many many thanks! I was using some other tokens/secret combination I believe.

Now there is just the wait to get my Elevated Twitter API request approved.
