### ISSUE TITLE
New Releases?

### ISSUE THREAD

**Issue by ErminMerdanovic** [souramoo/commentoplusplus#95]
Will new releases be released? The last one is from April last year. 

Since I'm having some trouble compiling it myself, or maybe someone has an easy guide for me to do it.

**Comment by souramoo** [comment]
Yep! Just merging in a github action workflow to make this process less manual and will be posted shortly :)

**Comment by souramoo** [comment]
Done. This should be far easier and more frequent going forward with the github action workflow.
