### ISSUE TITLE
i18n doesn't work

### ISSUE THREAD

**Issue by JadeVane** [souramoo/commentoplusplus#96]
Thank you for doing this amazing project, it provides many features that I want, that's great.

But I am now facing some small issues while using it. I added a file name zh.json which located in i18n folder, but I still got English when the page was flashed and commento++ had been reloaded.

I get no error in F12, so what can I do for it?

commento++: v1.8.7
browser: firefox 96.0 in ubuntu 20.04

**Comment by souramoo** [comment]
Thanks for the feedback! Happy to help you with this. Did you recompile the frontend code using `make`? If not, you will need to add the zh locale to the LOCALES string in the commento.js file if you are using the precompiled version. This string is automatically generated during the compilation process by gulp.

**Comment by JadeVane** [comment]
I added the zh.json file to the i18n folder and compiled it from the source code, the language is displayed successfully, thank you.
